version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    tty: true
    stdin_open: true
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    build: api/
    command: python main.py
    volumes:
      - .:/api
    ports:
      - "5000:5000"
    environment:
      - ENV=development
      - PORT=5000
      - LOCAL_DB=postgres://postgres:postgres@db:5432/postgres
      - SECRET_KEY=<YOUR SECRET KEY>
      - SQL_INIT_FILE=sql/init.sql
    depends_on:
      - db
  bot:
    build: bot/
    command: python bot.py
    volumes:
      - .:/bot
    environment:
      - TELEGRAM_SECRET_KEY=<YOUR TELEGRAM BOT SECRET KEY>
      - APP_BASE_URL=http://api:5000/
    depends_on:
      - api
volumes:
  db:
    driver: local
