version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    tty: true
    stdin_open: true
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local